# Generated by Django 3.2.13 on 2022-07-24 14:21

from django.db import migrations, models
import django.db.models.deletion
import django_models.fields
import django_models.utils.generators
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', django_models.fields.UUIDPrimaryKeyField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(default=functools.partial(django_models.utils.generators.generate_random_code, *(), **{'length': 16}), help_text='Product identifier', max_length=16, unique=True, verbose_name='SKU')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('code', models.CharField(default=functools.partial(django_models.utils.generators.generate_random_code, *(), **{'length': 8}), max_length=32, unique=True, verbose_name='Model code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', django_models.fields.UUIDPrimaryKeyField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cart.cart', verbose_name='Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='product.product', verbose_name='Product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
    ]
