# Generated by Django 3.2.13 on 2022-07-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='code',
        ),
    ]
