# Generated by Django 3.2.13 on 2022-07-24 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartproduct_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='code',
        ),
    ]
