# Generated by Django 3.2.13 on 2022-07-24 14:21

from django.db import migrations, models
import django_models.fields
import django_models.utils.generators
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('code', models.CharField(default=functools.partial(django_models.utils.generators.generate_random_code, *(), **{'length': 8}), max_length=32, unique=True, verbose_name='Model code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', django_models.fields.UUIDPrimaryKeyField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('host', models.CharField(blank=True, max_length=200, verbose_name='Host')),
                ('port', models.IntegerField(blank=True, verbose_name='Port')),
                ('username', models.CharField(blank=True, max_length=128, verbose_name='User')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='Password')),
                ('use_tls', models.BooleanField(default=False, verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('timeout', models.IntegerField(blank=True, default=10, verbose_name='Timeout')),
                ('ssl_keyfile', models.FileField(blank=True, null=True, upload_to='', verbose_name='SSL Keyfile')),
                ('ssl_certfile', models.FileField(blank=True, null=True, upload_to='', verbose_name='SSL Certfile')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('code', models.CharField(default=functools.partial(django_models.utils.generators.generate_random_code, *(), **{'length': 8}), max_length=32, unique=True, verbose_name='Model code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', django_models.fields.UUIDPrimaryKeyField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile_type', models.CharField(blank=True, choices=[('user', 'User'), ('store', 'Store')], max_length=18, null=True, verbose_name='Profile Type')),
                ('text', models.TextField(blank=True, verbose_name='Terms of Service text')),
            ],
            options={
                'verbose_name': 'Terms of Service',
                'verbose_name_plural': 'Terms of service',
            },
        ),
    ]
