# Generated by Django 3.2.13 on 2022-07-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smtpsettings',
            name='code',
        ),
        migrations.RemoveField(
            model_name='termsofservice',
            name='code',
        ),
    ]
