# Generated by Django 3.2.13 on 2022-07-24 14:21

from django.db import migrations, models
import django_models.fields
import django_models.utils.generators
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(default=functools.partial(django_models.utils.generators.generate_random_code, *(), **{'length': 8}), max_length=32, unique=True, verbose_name='Model code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', django_models.fields.UUIDPrimaryKeyField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('sku', models.CharField(default=functools.partial(django_models.utils.generators.generate_random_code, *(), **{'length': 6}), help_text='Product identifier', max_length=16, unique=True, verbose_name='SKU')),
                ('name', models.CharField(help_text='Product name', max_length=128, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
