# Generated by Django 3.2.13 on 2022-07-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
    ]
