# Generated by Django 3.2.13 on 2022-07-24 14:21

from django.db import migrations, models
import django_models.fields
import django_models.utils.generators
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', django_models.fields.UUIDPrimaryKeyField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(default=functools.partial(django_models.utils.generators.generate_random_code, *(), **{'length': 6}), help_text='Discount Coupon Identifier', max_length=16, unique=True, verbose_name='Code')),
                ('value', models.DecimalField(decimal_places=2, help_text='Product name', max_digits=9, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
