# Generated by Django 3.2.13 on 2022-07-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoupon',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Value', max_digits=9),
        ),
    ]
